(:name           "fastp")
(:repo           "taffish-org/fastp")
(:author         "KaiyuanHan")
(:version        "0.24.0")
(:intro          "An ultra-fast all-in-one FASTQ preprocessor (QC/adapters/trimming/filtering/splitting/merging...).")
(:dependencies)
(:functions      "fastp")
